### ISSUE TITLE
Watchnixtoons2

### ISSUE THREAD

**Issue by Katkiller316** [doko-desuka/doko-desuka.github.io#3]
hi  having trouble with this addon
it loads up ok but cant get any anime lists as it errors 

I know there is an error log file but don't know how to get it or upload it to here

any help much appreciated as this addon is the best

**Comment by doko-desuka** [comment]
You can open future issues on the Watchnixtoons2 repo: https://github.com/doko-desuka/plugin.video.watchnixtoons2

Anyway, I went to Subbed Anime -> Boku no Hero Academia and played a random episode, it's working.  

So what you're experiencing is probably that your internet service is off. The initial menu screen with all the categories doesn't use the internet yet, it's only when you try to go into a category (like Subbed Anime for instance) that it uses the web.  
I'm closing this issue, but if you discover anything new just comment in here again and I'll see it.
