### ISSUE TITLE
Patments

### ISSUE THREAD

**Issue by terrormaniac22** [doko-desuka/doko-desuka.github.io#4]
Where can i pay to watch?? Today in the morning this addon was stopped playing and says that i must pay but where can i do that or is it an bug please helpp 
![IMG_20200329_175532](https://user-images.githubusercontent.com/57250252/77853848-b61d1f00-71e6-11ea-951e-04969c282ec1.jpg)

**Comment by fade2gray** [comment]
Do you have your addon settings to allow for automatic updating of addons? Check what version of NixToons you currently have. I am not having any problems with version 0.44, but I am being notified that version 0.45 is waiting to be installed.

**Comment by terrormaniac22** [comment]
I have automatic installation on. Can i downgrade the addon to 0.44 ??

**Comment by doko-desuka** [comment]
The site seems back online, so I updated WNT2 to version 0.4.6 that removes that paywall notice.  

If you have set "automatic updates" on in your Kodi, you should be getting it. If that setting is not on you should still see it in your add-on updates list, just go there and click to update.  
You can read all about it in here: https://kodi.wiki/view/Add-on_manager#Updating

You can also manually download the WNT2 add-on package from here, and "Install from zip file" in Kodi: https://github.com/doko-desuka/plugin.video.watchnixtoons2
