### ISSUE TITLE
Doko Repository "Could not connect to repository"

### ISSUE THREAD

**Issue by itsacuppycake** [doko-desuka/doko-desuka.github.io#5]
Installing the addon to a new firestick (4k) and I've done this a million times but I'm not sure what I'm doing wrong this time or if there's an issue. It says the zip installs fine but once I install from repository, no luck

**Comment by doko-desuka** [comment]
Hi @itsacuppycake , this was my fault. The `addons.xml` file of my repository was missing a closing tag.  
I've fixed it now, thanks for the report.

**Comment by itsacuppycake** [comment]
@doko-desuka awesome, thank you! I'm just happy it wasn't anything on my end

**Comment by itsacuppycake** [comment]
@doko-desuka hi again, I'm not seeing any video add-ons in the repository,  just 'program add ons' and 'addon repository'. The source is still https://doko-desuka.github.io right?

**Comment by fade2gray** [comment]
@itsacuppycake [see](https://www.reddit.com/r/Addons4Kodi/comments/hc69ss/doko_addon/)

**Comment by itsacuppycake** [comment]
@fade2gray thank you!
